---
# ==============================================================================
# Constants
# ==============================================================================

# full core components list, they should show up in components section in zowe.yaml
zowe_core_components:
- gateway
- cloud-gateway
- metrics-service
- api-catalog
- discovery
- caching-service
- app-server
- zss
- jobs-api
- files-api
- explorer-jes
- explorer-mvs
- explorer-uss

# this should list all known cross memory server stc we ever setup during install
zowe_known_xmem_proc_stcs:
- ZWESIS01
- ZWEXMSTC
- ZWESISTC

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
# temporary folder on remote
work_dir_remote:
# default zowe runtime root directory
zowe_root_dir: ~/zowe
# if your z/OS system has VSAM RLS (record level sharing) enabled.
# usually this value should be true in Parallel Sysplex.
zos_vsam_rls: false
# dataset prefix where zowe will be installed
zowe_dataset_prefix:
# instanceDir
zowe_instance_dir: ~/.zowe/instance
# install logs directory
zowe_install_logs_dir: ~/.zowe/logs
# zowe job prefix.
zowe_job_prefix: ZWE
# instance id. This will be put into zowe job name after {{ zowe_job_prefix }}
zowe_instance_id: 1
# default z/OSMF port. Optional, default value is ansible_ssh_host
zos_zosmf_host:
# default z/OSMF port
zos_zosmf_port: 10443
# default z/OSMF user
zos_zosmf_user: IZUSVR
# default z/OSMF Certificate Authority
zos_zosmf_ca:
# APIML ports
zowe_apiml_metrics_service_port: 7551
zowe_apiml_catalog_port: 7552
zowe_apiml_discovery_port: 7553
zowe_apiml_gateway_port: 7554
zowe_apiml_cloud_gateway_port: 7563
zowe_apiml_verify_certficates_of_services: true
zowe_apiml_nonstrict_verify_certficates_of_services: true
# APIML configuration properties
zowe_apiml_gateway_timeout_millis: 600000
zowe_apiml_security_x509_enabled: false
zowe_apiml_security_zosmf_applid: IZUDFLT
zowe_apiml_security_auth_provider: zosmf
zowe_apiml_security_zosmf_jwt_autoconfiguration_mode: auto
zowe_apiml_security_oidc_enabled: false
zowe_apiml_security_oidc_client_id:
zowe_apiml_security_oidc_client_secret:
zowe_apiml_security_oidc_registry:
zowe_apiml_security_oidc_introspect_url:
# explorer APIs/plugins ports
zowe_jobs_api_port: 7558
zowe_mvs_api_port: 7559
zowe_jobs_explorer_port: 7560
zowe_mvs_explorer_port: 7561
zowe_uss_explorer_port: 7562
# caching service
zowe_caching_service_port: 7555
zowe_caching_service_persistent: VSAM
# the final data set name will be: {zowe_dataset_prefix}.{zowe_caching_service_vsam_dsprefix}{zowe_instance_id}
# for example: IBMUSER.ZWE.CACHE1
zowe_caching_service_vsam_dsprefix: CACHE
zowe_caching_vsam_storage_class:
zowe_caching_vsam_volume:
# zlux ports
zowe_zlux_port: 7556
zowe_zss_https: True
zowe_zss_port: 7557
# make sure that this equals to zssCrossMemoryServerName in install in zowe-install-apf-server.yaml
zowe_zss_xmem_name: ZWESIS_STD
zowe_zlux_terminal_ssh_port: 22
zowe_zlux_terminal_telnet_port: 23
# The security type of the tn3270 connection - valid values are blank('') for telnet, or 'tls'
zowe_zlux_terminal_telnet_security_type:
zowe_zosmf_certificate:
zowe_external_certficate:
zowe_external_certficate_alias:
zowe_external_certficate_authorities:
zowe_keystore_dir: ~/.zowe/keystore
zowe_keystore_password: password
zowe_keyring_alias: ZoweKeyring
zowe_keyring_certname: ZoweCert
zowe_keyring_external_intermediate_ca:
zowe_keyring_external_root_ca: brcmso
zowe_keystore_alias: localhost
zowe_jcllib:
zowe_proclib_dsname: auto
zowe_proclib_membername: ZWESLSTC
zowe_runtime_user: ZWESVUSR
zowe_runtime_group: ZWEADMIN
zowe_auto_create_user_group: false
# if we want to skip executing ZWESECUR job
zowe_configure_security_dry_run: false
# if we want to ignore zwesecur job failure
zowe_configure_ignore_security_failures: false

################################################################################
# these are default variables for cross memory configuration
zowe_xmem_proclib:
zowe_xmem_parmlib:
# this is optional, it will fall back to {{zowe_dataset_prefix}}.SZWEAUTH
zowe_xmem_loadlib:
zowe_xmem_pluginlib:
zowe_xmem_proclib_member_zss: ZWESISTC
zowe_xmem_proclib_member_aux: ZWESASTC
zowe_xmem_stc_user: ZWESIUSR
zowe_xmem_stc_group: ZWEADMIN

# optional, default to ansible_ssh_host
# required for zD&T (external IP is different from internal IP)
zowe_zos_host:
# optional, default to zowe_zos_host
# for z/OS deployment, this can be left empty and be same as zowe_zos_host
# for all-in-one docker deployment, this can be set to domain where you start docker container
zowe_external_domain_name:
# optional, no default value
# required for zD&T (external IP is different from internal IP)
zowe_external_ip_address:
# Restrict permissions to keystore/truststore after the certificate setup script
zowe_lock_keystore: true
# comma separated string
zowe_launch_components:
# log level for Zowe launch scripts
zowe_launch_scripts_loglevel: 

# turn config manager on or off
zowe_use_config_manager: true
