---
# our zD&T instances are located at this server
ansible_ssh_host: river.zowe.org

################################################################################
# variables for zowe uninstallation and installation
work_dir_remote: /zaas1/zowe/ansible
zowe_fmids_dir_remote: /zaas1/zowe/fmids
zowe_external_domain_name: river.zowe.org
zowe_external_ip_address: 37.58.118.251
zowe_root_dir: /zaas1/zowe/runtime
zowe_instance_dir: /zaas1/zowe/instance
zowe_keystore_dir: /zaas1/zowe/keystore
zowe_dataset_prefix: TSTRADM.ZWE
zowe_apiml_verify_certficates_of_services: false
zowe_proclib_dsname: ZAAS1.PROCLIB
zowe_xmem_proclib: ZAAS1.PROCLIB
zowe_xmem_loadlib: TSTRADM.LOADLIB
zowe_xmem_parmlib: TSTRADM.PARMLIB
# variables for zowe smpe uninstallation and installation
# during uninstallation, any data-sets start with {this}.ZOWE.{fmid} will be removed
zowe_smpe_hlq_dsn: ZOWE
# during uninstallation, any data-sets start with this will be removed
zowe_smpe_hlq_csi: ZOWE.SMPE
zowe_smpe_hlq_tzone: ZOWE.SMPE
zowe_smpe_hlq_dzone: ZOWE.SMPE
zowe_smpe_dir_prefix: /zaas1/zowe/runtime
zowe_smpe_rel_file_prefix: ZOWE
zowe_smpe_volser: B3IME1
