---
ansible_ssh_host: wlag.svl.ibm.com
ansible_user: 
ansible_password: 

################################################################################
zowe_fmids_dir_remote: /var/zowe/zowe-fmids
work_dir_remote: /var/zowe/ansible
zowe_root_dir: /var/zowe/runtime
zowe_instance_dir: /var/zowe/zowe-instance-dir
zowe_keystore_dir: /var/zowe/keystore
zowe_logs_dir: /var/zowe/logs
zowe_install_logs_dir: /var/zowe/logs

zowe_dataset_prefix: ZWE.V1R0M0
zowe_apiml_verify_certficates_of_services: false
zowe_proclib_dsname: DSWMG.PROCLIB
zowe_xmem_proclib: DSWMG.PROCLIB
# this variable is deprecated in favor of zowe_dataset_prefix
zowe_xmem_loadlib: CLJIA.LOADLIB
zowe_xmem_parmlib: CLJIA.PARMLIB
# variables for zowe smpe uninstallation and installation
# during uninstallation, any data-sets start with {this}.ZOWE.{fmid} will be removed
zowe_smpe_hlq_dsn: ZOE
# during uninstallation, any data-sets start with this will be removed
zowe_smpe_hlq_csi: ZOE.SMPE
zowe_smpe_hlq_tzone: ZOE.SMPE
zowe_smpe_hlq_dzone: ZOE.SMPE
zowe_smpe_dir_prefix: /var/zowe/runtime

zowe_extra_environment_variables:
  # SVL image has an error when executing netstat
  # EZZ2376I Could not determine TCPIPjobname, using default of 'INET'
  # EZZ2377I Could not establish affinity with INET (1011/11B3005A) - can not provide the requested option information
  # to fix it, this variable is required
  RESOLVER_CONFIG: "\"//'USER.PARMLIB(TCPDATA)'\""

# variables for zowe uninstallation and installation
zowe_smpe_volser: WLAG1

zowe_external_domain_name: wlag.svl.ibm.com
zowe_external_ip_address: 9.30.238.55
