---
# Transfer and submit ZWECCADD JCL to map client certificate to user in ACF2

- name: Remove ZWECCADD.jcl if exists
  raw: rm -f "{{ work_dir_remote }}/ZWECCADD.jcl"

- name: Transfer ZWECCADD.jcl to zOS
  block:
    - import_role:
        name: common
        tasks_from: validate_variables
      vars:
        variable_list:
          - dataset
          - label

    - name: Copy ZWECCADD.jcl to local tmp folder
      copy:
        src: ZWECCADD.jcl
        dest: "{{ work_dir_local }}/{{ inventory_hostname }}/"
      delegate_to: localhost

    - import_role:
        name: common
        tasks_from: upload_file
      vars:
        filename_to_upload: ZWECCADD.jcl
        file_upload_method: scp
        file_upload_hashcheck: false

    - name: Check if ZWECCADD.jcl exists on zOS
      raw: test -f "{{ work_dir_remote }}/ZWECCADD.jcl"
      ignore_errors: True
      register: file_exist
      failed_when: file_exist.rc != 0

- name: Update ZWECCADD.jcl with configurations
  raw: >-
    cat "{{ work_dir_remote }}/ZWECCADD.jcl" | \
    sed -e "s+ZOWEUSER=ZWESVUSR+ZOWEUSER={{ zowe_runtime_user }}+" | \
    sed -e "s+SUFIX=+SUFIX={{ dataset }}+" | \
    sed -e "s+LABEL(&LABEL.)+LABEL({{ label }})+" | \
    sed -e "s+DSNAME=ZOWE+DSNAME={{ zowe_dataset_prefix }}.CERT.{{ dataset }}+" \
    > "{{ work_dir_remote }}/ZWECCADD.jcl"

- name: Check ZWECCADD.jcl changes
  raw: cat "{{ work_dir_remote }}/ZWECCADD.jcl"

- name: Run ZWECCADD.jcl
  import_role:
    name: zos
    tasks_from: run_jcl
  vars:
    jcl_filename: "{{ work_dir_remote }}/ZWECCADD.jcl"
