---
# this playbook will copy Zowe proc
- name: Install Zowe Proc
  import_role:
    name: zos
    tasks_from: run_script
  vars:
    script_chdir: "{{ zowe_root_dir }}/scripts/utils"
    script_filename: ./zowe-install-proc.sh
    script_parameters: "-d \"{{ zowe_dataset_prefix }}\" -r \"{{ zowe_proclib_dsname }}\""
