---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: apiml
    app.kubernetes.io/managed-by: manual
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/component: discovery
  ports:
    - name: discovery
      protocol: TCP
      port: 7553
      targetPort: discovery-port
      appProtocol: https
