---
# ==============================================================================
# Constants
# ==============================================================================
# work folder on local, we will store some temporary files here
work_dir_local: .tmp
zos_uss_user_profile: ~/.profile

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
zowe_root_dir: ~/zowe
zowe_instance_dir: ~/.zowe/instance
zowe_extension_dir: ~/zowe/extensions
# install logs directory
zowe_install_logs_dir: ~/.zowe/logs
