apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: apiml
    app.kubernetes.io/managed-by: manual
spec:
  # FIXME: you can uncomment and modify this line if you have your own domain name.
  # host: my-domain-name.com
  to:
    kind: Service
    name: gateway-service
  tls:
    termination: passthrough
  wildcardPolicy: None
