---
# ==============================================================================
# Constants
# ==============================================================================
# work folder on local, we will store some temporary files here
work_dir_local: .tmp

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
# if run test in debug mode. for example, set to "test:*"
zowe_sanity_test_debug_mode: ""
# only run subset of test cases
zowe_sanity_test_testcases: "\"./test/**/!(api-doc-gen).js\" --exclude ./**/test-zss-via-gateway.js --exclude ./**/test-caching-service-apis-via-gateway.js --exclude ./**/test-oidc-via-gateway.js --exclude ./**/test-zlux-server.js "
# default folder of sanity test
zowe_sanity_test_root_dir: ../tests/sanity

# default z/OSMF port
zos_zosmf_port: 10443

# default zowe runtime root directory
zowe_root_dir: ~/zowe
# instanceDir
zowe_instance_dir: ~/.zowe/instance
# zowe job prefix.
zowe_job_prefix: ZWE
zowe_proclib_membername: ZWESLSTC
zowe_instance_id: 1
# ports will be tested
zowe_apiml_gateway_port: 7554
zowe_zlux_port: 7556
