---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: apiml
    app.kubernetes.io/managed-by: manual
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/component: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 7554
      targetPort: gateway-port
      appProtocol: https
